him = getattr(__import__('handy'),'him')
__ = him({'utilities':('mtf',), 'bt':('LF',), 'os':('linesep',)})
for _ in list(__.keys()):exec("%s=__['%s']"%(_,_))
fit = 'mhi'
pf = mtf(fit)
mpd = getattr(lf(pf),'fp')
print('%s: (latest @ %s)'%(pf,mpd.trade_day[-1]))
print(getattr(mpd,'xfinder')('d'))
print(getattr(mpd,'xfinder')('r'))
ar, mos = getattr(mpd,'fdc')('b'), getattr(mpd,'ltdmos')('a')
lv, vm, vs = ar['Volume'].values[-1], ar['Volume'].mean(), ar['Volume'].std()
print("%sVolume over mean: %.2f%%" % (linesep, lv / vm* 100.))
print("Volume over (mean + std): %.2f%%" % (lv / (vm +vs) * 100.))
lc, cs = ar['Close'].values[-1], ar['Close'].std()
il = list(filter(lambda _:(_ > lc - cs) and (_ < lc + cs), mos))
ol = list(filter(lambda _:(_ < lc -cs) or (_ > lc + cs), mos))
print('%sLast Close: %i' % (linesep, lc))
print('%sWithin statistical range:' % linesep, il)
ml = list(filter(lambda _:_ > lc, ol))
csl = list(filter(lambda _:_ not in ml, ol))
print('%sMoon shot:' % linesep, ml)
print('China syndrome:', csl)
